import Head from 'next/head'
import styled from "styled-components"
// import fetch from "isomorphic-fetch"

//styled components
const MainStyled = styled.div`
text-align: center;
`
const defaultEndpoint = "https://rickandmortyapi.com/api/character"
export const getStaticProps = async () => {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return{
    props:{
      data
    }
  }
};

export default function Home({data}) {
  console.log("res", data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainStyled>
      <h1>
        the rick and morty
      </h1>
        <p>
          Kimo Khan 1985{' '} 
        </p>
      </MainStyled>
    </>
  )
}
