import Head from 'next/head'
import styled from "styled-components"
import fetch from "isomorphic-fetch"
import { Card } from './rickMorty/Card'

//styled components
const MainStyled = styled.main`
text-align: center;
margin-top: 5%;
 .grid{
display: flex;
align-items: center;
justify-content: center;
flex-wrap: wrap;
padding: 0;
 }
`
// const defaultEndpoint = "https://rickandmortyapi.com/api/character"
export const getStaticProps = async () => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const data = await res.json();
  const results = data?.results?.map(
    ({ id, name, status, species, location, image }) => ({
      id,
      name,
      status,
      species,
      location: location.name,
      image,
    })
  );
  if (!results) return { props: { results: [] } };
  return { props: { results } };
};

export default function Home({ results = [] }) {
  // const { results = [] } = data;
  // const { info, results : defulteResults = [] } = data;
  // const [resul, updateResul] = useState(results)
  console.log("info", results)
  // console.log("rdefulteResults", defulteResults)
  // const [page, updatePage] = useState({
  //   ...info,
  //   current: defaultEndpoint
  // });
  // const {current} = page;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainStyled as="main">
        <h1>
          Wubba Lubba Dub dub!
        </h1>
        <p>
          the rick and morty
        </p>
        <ul className='grid' >
          {results.map((resul) => (
            //Card page
            <Card key={resul.id} {...resul} />
          ))}
        </ul>
      </MainStyled>
    </>
  )
}
