import Head from 'next/head'
import styled from "styled-components"
// import fetch from "isomorphic-fetch"
// import Image from "next/image"
// import Link from 'next/link'

//styled components
const MainStyled = styled.main`
text-align: center;
.grid{
display: flex;
align-items: center;
justify-content: center;
flex-wrap: wrap;
padding: 0;
.cart{
  list-style-type: none;
  margin: 10px;
  padding: 0;
}

}
`
const defaultEndpoint = "https://rickandmortyapi.com/api/character"
export const getStaticProps = async () => {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
};

export default function Home({ data }) {
  const { results = [] } = data;
  console.log("res", results)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainStyled as="main">
        <h1>
          Wubba Lubba Dub dub!
        </h1>
        <p>
          the rick and morty
        </p>
        <ul className='grid' >
          {results.map(result => {
            const { id, name, image } = result;
            return (
              <li key={id} className="cart">
              <a href="">
                <img src={image}  alt={`${name}`} />
                <h3>
                  {name}
                </h3>
              </a>
            </li>
            )
          })}


        </ul>
      </MainStyled>
    </>
  )
}
